# Generated by Django 4.2 on 2025-09-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
