# Generated by Django 4.2 on 2025-09-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
